language: go

go:
  - 1.13.x

cache:
  directories:
    - .cache

script: |
  mkdir -p .cache && export GOPATH=$(pwd)/.cache
  CGO_ENABLED=0 GO111MODULE=on go test -cover -covermode=atomic -coverprofile=coverage.txt -v ./...

after_script: |
  bash <(curl -s https://codecov.io/bash)
