name: Go
on:
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test
        run: |
          export GOPATH=~/.cache
          CGO_ENABLED=0 GO111MODULE=on go test -cover -covermode=atomic -coverprofile=coverage.txt -v ./...
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
